### ISSUE TITLE
想请问下有什么开源的语音转文字的对话数据集吗？

### ISSUE THREAD

**Issue by Violettttee** [YouTaoBaBa/-#1]
如题，想请问有什么开源的语音转文字的对话数据集吗？不需要语音，只需要转文字后的结果，最好是有对话的。

**Comment by YouTaoBaBa** [comment]
都不需要语音了为什么还要asr的数据集呀，直接文字的对话数据集不可以吗，我理解你是想要更口语化的对话数据集？这两个可以参考下，我没有实际使用过
[https://github.com/aim3-ruc/rucm3ed](url)
[https://github.com/scutcyr/CPED?tab=readme-ov-file](url)

**Comment by Violettttee** [comment]
> 都不需要语音了为什么还要asr的数据集呀，直接文字的对话数据集不可以吗，我理解你是想要更口语化的对话数据集？这两个可以参考下，我没有实际使用过
> [https://github.com/aim3-ruc/rucm3ed](url)
> [https://github.com/scutcyr/CPED?tab=readme-ov-file](url)

对的，是想要更口语化的数据集。我试试你发的看看～

**Comment by hppy139** [comment]
@YouTaoBaBa @Violettttee 两个地址已失效，可以重新分享一下吗？谢谢~
